tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
brew "ctop"
brew "ffmpeg"
brew "fish"
brew "fnm"
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "handbrake"
brew "jsonpp"
brew "mas"
brew "ripgrep"
brew "starship"
brew "trash"
brew "wakeonlan"
brew "yt-dlp"
cask "1password"
cask "arc"
cask "asset-catalog-tinkerer"
cask "calibre"
cask "discord"
cask "figma"
cask "firefox"
cask "font-metropolis"
cask "google-chrome"
cask "handbrake"
cask "iterm2"
cask "kap"
cask "mullvadvpn"
cask "notion"
cask "parsec"
cask "steam"
cask "tableplus"
cask "telegram"
cask "the-unarchiver"
cask "tor-browser"
cask "tower"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
mas "1Password for Safari", id: 1569813296
mas "Balance Lock", id: 1019371109
mas "BetterSnapTool", id: 417375580
mas "ColorSlurp", id: 1287239339
mas "Deliveries", id: 290986013
mas "GarageBand", id: 682658836
mas "Hand Mirror", id: 1502839586
mas "iMovie", id: 408981434
mas "Keyboard Keyboard", id: 1128271725
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "NepTunes", id: 1006739057
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Tweetbot", id: 1384080005
mas "WireGuard", id: 1451685025
vscode "aaron-bond.better-comments"
vscode "adamwalzer.string-converter"
vscode "adpyke.vscode-sql-formatter"
vscode "alexdima.copy-relative-path"
vscode "amodio.toggle-excluded-files"
vscode "apollographql.vscode-apollo"
vscode "ardenivanov.svelte-intellisense"
vscode "be5invis.vscode-icontheme-nomo-dark"
vscode "bmalehorn.vscode-fish"
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.npm-intellisense"
vscode "cmstead.js-codeformer"
vscode "codezombiech.gitignore"
vscode "csstools.postcss"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-close-tag"
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"
vscode "GitHub.copilot-labs"
vscode "GitHub.github-vscode-theme"
vscode "github.vscode-github-actions"
vscode "GitHub.vscode-pull-request-github"
vscode "golang.go"
vscode "johnpapa.vscode-peacock"
vscode "mhutchie.git-graph"
vscode "midnightsyntax.vscode-wrap-console-log"
vscode "mikestead.dotenv"
vscode "mrmlnc.vscode-json5"
vscode "mrmlnc.vscode-scss"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "ms-vsliveshare.vsliveshare"
vscode "phoenisx.cssvar"
vscode "Prisma.prisma"
vscode "richie5um2.vscode-sort-json"
vscode "SimonSiefke.svg-preview"
vscode "skyapps.fish-vscode"
vscode "syler.sass-indented"
vscode "tamasfe.even-better-toml"
vscode "timonwong.shellcheck"
vscode "tombonnike.vscode-status-bar-format-toggle"
vscode "unifiedjs.vscode-mdx"
vscode "usernamehw.errorlens"
vscode "vscode-icons-team.vscode-icons"
vscode "Vue.volar"
vscode "Vue.vscode-typescript-vue-plugin"
vscode "wmaurer.change-case"
vscode "ybaumes.highlight-trailing-white-spaces"
vscode "ZixuanChen.vitest-explorer"
