# --- General ---
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -s escape-time 0

# --- Prefix ---
unbind C-b
set-option -g prefix `
bind-key ` send-prefix
bind-key `` send-keys `

# --- Mouse ---
set -g mouse on

# --- Status bar ---
set -g status-style "bg=green,fg=#000000"
