tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "miralize/tap", "https://github.com/miralize/homebrew-tap.git"
brew "ctop"
brew "fish"
brew "fnm"
brew "gh"
brew "gist"
brew "git"
brew "go"
brew "mas"
brew "mkcert"
brew "nss"
brew "python@3.7"
brew "starship"
brew "youtube-dl"
cask "docker2"
cask "epoccam"
cask "gitfox"
cask "google-chrome"
cask "iterm2"
cask "notion"
cask "raycast"
cask "tableplus"
cask "telegram"
cask "visual-studio-code"
mas "BetterSnapTool", id: 417375580
mas "Deliveries", id: 290986013
mas "NepTunes", id: 1006739057
mas "Tweetbot", id: 1384080005
